### ISSUE TITLE
what's the difference between DAT and deformable DETR's attention?

### ISSUE THREAD

**Issue by jinfagang** [LeapLabTHU/DAT#18]
what's the difference between DAT and deformable DETR's attention?

**Comment by Vladimir2506** [comment]
@jinfagang Please check Part A. in the Appendix of our paper.

**Comment by jinfagang** [comment]
@Vladimir2506 thanks for point it out. I see that DAT's code didn't using any c++ customized layer or op while deformableDETR using customized code to implement their deformable, why ?

**Comment by Vladimir2506** [comment]
@jinfagang Because the spatial sampling operation in DAT is relatively simple and can be directly implemented by `F.gridsample(feature, pos)` with a feasible speed, while Deformable-DETR provides a more optimized CUDA OP version for different numbers of keys. Therefore, there could be an optimized CUDA implementation for DAT if low latency is in demand.
