### ISSUE TITLE
About the range of offset

### ISSUE THREAD

**Issue by Chris-city** [LeapLabTHU/DAT#31]
Thank you for your work! 
I have a question, whether the range of offset is related to the kernel size of offset_conv, for example, whether the offset_conv of 3*3 can only consider the offset of only one point around each pixel in that feature map layer?

**Comment by Vladimir2506** [comment]
Hello @Chris-city,

Thank you for your interest in our work. Conceptually, the offset range has nothing to do with the offset generator. The offset generator mainly considers the area covered by the kernel in DWC, but due to the processing by previous transformer blocks, it is reasonable that one reference point learns a much larger offset value than the kernel size. 

Therefore, the restriction of offset range in the conference version of DAT is unnecessary and we remove it for a neat design in the new version DAT++.
